apiVersion: apps/v1
kind: Deployment
metadata:
  name: aquilacms-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aquilacms-app
  template:
    metadata:
      labels:
        app: aquilacms-app
    spec:
      containers:
      - name: aquilacms-app
        image: ${{ secrets.DOCKER_USERNAME }}/aquilacms:latest
        ports:
        - containerPort: 3010
        env:
        - name: PORT
          value: "3010"
        - name: MONGO_URL
          value: "mongodb://aquilacms-db-service:27017"
---
apiVersion: v1
kind: Service
metadata:
  name: aquilacms-app-service
spec:
  type: LoadBalancer
  ports:
  - port: 3010
    targetPort: 3010
  selector:
    app: aquilacms-app
