apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: aquila-db
spec:
  serviceName: "aquila-db-service"
  replicas: 1
  selector:
    matchLabels:
      app: aquila-db
  template:
    metadata:
      labels:
        app: aquila-db
    spec:
      containers:
      - name: aquila-db
        image: bitnami/mongodb:latest
        ports:
        - containerPort: 27017
        volumeMounts:
        - name: aquila-db-storage
          mountPath: /data/db
  volumeClaimTemplates:
  - metadata:
      name: aquila-db-storage
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 10Gi

---

apiVersion: v1
kind: Service
metadata:
  name: aquila-db-service
spec:
  ports:
  - port: 27017
    targetPort: 27017
  selector:
    app: aquila-db

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: aquila-db-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
  hostPath:
    path: "/mnt/data/aquila-db"
