name: Build and Deploy AquilaCMS to EC2

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: yarn install

    - name: Build Docker image
      run: docker build -t aquilacms .

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Push Docker image
      run: |
        docker tag aquilacms:latest ${{ secrets.DOCKER_USERNAME }}/aquilacms:latest
        docker push ${{ secrets.DOCKER_USERNAME }}/aquilacms:latest

  # deploy:
  #   needs: build
  #   runs-on: ubuntu-latest

  #   steps:
  #   - name: SSH into EC2 and deploy
  #     uses: appleboy/ssh-action@v0.1.6
  #     with:
  #       host: ${{ secrets.EC2_HOST }}
  #       username: ${{ secrets.EC2_USER }}
  #       key: ${{ secrets.EC2_SSH_KEY }}
  #       script: |
  #         docker pull ${{ secrets.DOCKER_USERNAME }}/aquilacms:latest
  #         docker stop aquila || true
  #         docker rm aquila || true
  #         docker run -d --name aquila -p 3010:3010 \
  #         --env MONGO_URI=mongodb://{{ secrets.DB_HOST }}:27017/your-database-name \
  #         ${{ secrets.DOCKER_USERNAME }}/aquilacms:latest
