name: Build and Deploy AquilaCMS to EC2

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: yarn install

    - name: Build Docker image
      run: docker build -t aquilacms .

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Push Docker image
      run: |
        docker tag aquilacms:latest ${{ secrets.DOCKER_USERNAME }}/aquilacms:latest
        docker push ${{ secrets.DOCKER_USERNAME }}/aquilacms:latest

  deploy:
    needs: build
    runs-on: self-hosted

    steps:
    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.7.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Add Bastion Host to known_hosts
      run: ssh-keyscan -H ${{ secrets.BASTION_HOST }} >> ~/.ssh/known_hosts

    - name: Add Private EC2 Instance to known_hosts
      run: ssh-keyscan -H ${{ secrets.PRIVATE_APP_HOST }} >> ~/.ssh/known_hosts

    - name: Deploy to Private EC2 Instance via Bastion
      run: |
        ssh -o ProxyCommand="ssh -W %h:%p ec2-user@${{ secrets.BASTION_HOST }}" ec2-user@${{ secrets.PRIVATE_APP_HOST }} << EOF
          cd /path/to/your/app
          git pull origin main
          npm install
          npm run start
        EOF