name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # - name: Set up Docker Buildx
      #   uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # - name: Build Docker image
      #   run: |
      #     docker build -t ${{ secrets.DOCKER_USERNAME }}/aquilacms-app:latest .

      # - name: Push Docker image to Docker Hub
      #   run: |
      #     docker push ${{ secrets.DOCKER_USERNAME }}/aquilacms-app:latest
      - name: Encode Kubeconfig (example)
        run: |
          cat ~/.kube/config | base64 -w 0  # store output in a variable
          echo "##@ mask kubeconfig"  # mask the variable in logs
          echo "KUBECONFIG_BASE64=$(base64 -w 0 ~/.kube/config)" >> $GITHUB_ENV

      - uses: tale/kubectl-action@v1
        with:
          base64-kube-config: ${{ env.KUBECONFIG_BASE64 }} # reference the masked variable
          kubectl-version: latest

      - name: Update Kubernetes Deployment
        run: |
          aws eks update-kubeconfig --name ${{ secrets.EKS_CLUSTER_NAME }} --region ${{ secrets.EKS_CLUSTER_REGION }}
          kubectl set image deployment/aquilacms-app aquilacms-app=${{ secrets.DOCKER_USERNAME }}/aquilacms:latest

          kubectl apply -f k8s/app-deployment.yaml
          kubectl apply -f k8s/db-deployment.yaml
