name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # - name: Set up Docker Buildx
      #   uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # - name: Build Docker image
      #   run: |
      #     docker build -t ${{ secrets.DOCKER_USERNAME }}/aquilacms-app:latest .

      # - name: Push Docker image to Docker Hub
      #   run: |
      #     docker push ${{ secrets.DOCKER_USERNAME }}/aquilacms-app:latest
      - name: Apply Kubernetes manifest
        uses: aws-actions/eks-kubectl@v1
        with:
          cluster-name: aquila-cluster
          kubeconfig-file: ~/.kube/config

      - name: Update Kubernetes Deployment
        run: |
          aws eks update-kubeconfig --name ${{ secrets.EKS_CLUSTER_NAME }} --region ${{ secrets.EKS_CLUSTER_REGION }}
          kubectl set image deployment/aquilacms-app aquilacms-app=${{ secrets.DOCKER_USERNAME }}/aquilacms:latest

          kubectl apply -f k8s/app-deployment.yaml
          kubectl apply -f k8s/db-deployment.yaml
